infra:
  exp_name: mutimodal
  log_dir: log
  comment: dev
  log_gpu: false
  seed: 1000
  # SLURM_GPUS_ON_NODE: 1
  # SLURM_JOB_NUM_NODES: 1

data:
  set: nzsrh
  direct_params:
    common:
      data_root: 
      segmentation_model: 03207B00
      num_transforms: 1
    train:
      slides_file: 
    val:
      slides_file: 
  save_instances: False
  primary_label_index: 0
  discrimination_type: patch
  nz_filter:
    which: include_all
    params:
      count: 1
      stride: 1
  augmentations:
    prob: 0.3
    train:
    - which: nz_centercrop_alwaysapply
      params:
        size: 256
    - which: nz_random_horiz_flip
      params: {}
    - which: nz_random_vert_flip
      params: {}
    val: same
loader:
  direct_params:
    common:
      pin_memory: True
      prefetch_factor: 10
      num_workers: 4
    train:
      batch_size: 4
      drop_last: True
      shuffle: True
    val:
      batch_size: 1
      drop_last: False
      shuffle: False
  val_sampler:
    num_samples: 20
    replacement: False
model:
  which: CL2L_VITB16
  params:
    attn-layer: 'flash'
    no-share-token: False
    semi-paired: False
    embed-dim: 256
    clip-hidden-dim: 4096
    unpaired-ratio: 4
    ssl-scale: 1.0
    ssl-temp:  0.1
    resume: ''
    init-text-encoder: None
    detach-proj: False
    momentum: False
    momentum-tau: 0.99
    transformer-layers: 12
    clip-proj-type: 'linear'
    cl2l-txt-proj-type: 'mlp'
    cl2l-img-proj-type: 'mlp'
    separate-proj: False
    separate-proj-child: False
    ddconfig:
      barlip-proj-dim: 8192
      barlip-hidden-dim: 3000
      barlip-lamb: 5e-3
      barlip-scale-loss: 0.025



training:
  num_epochs: 5
  warmup-epochs: 1
  start-epoch: 0
  batch-size: 64
  lr: 3e-3
  lr-start: 1e-6
  lr-end: 1e-5
  update-freq: 1
  wd: 0.1
  betas: 0.9 0.98
  eps: 1e-8
  eval-freq: 1
  disable-amp: false
  loss-avg-or-sum: 'avg'
  checkpoint-grad: False

system:
  print-freq: 25
  workers-unpaired: 5
  evaluate: False
  world-size: 1
  rank: 0
  local_rank: 0
  dist-url: 'env://'
  dist-backend: 'nccl'
  seed: 0
  gpu: None
  wandb: False
  offline: False
  name: 'CLIP_ROCKET'


  

